language: node_js
node_js:
  - 'node'
before_install:
  - sudo apt-get -y install cargo
  - cargo --version
  - rustc --version
brefore_script:
  - pushd ./rust-test-helper
  - cargo build
  - popd
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
